def get_personagens():
    personagens = [
        {
            "nome": "Fred",
            "humano": True,
            "homem": True,
            "ruivo": False,
            "oculos": False,
            "loiro": True,
            "fome": False,
            "dirige": True,
            "rabo": False,
            "coragem": True,
            "espada": False,
            "capuz": False,
            "aventura": False,
            "princesa": False,
            "vampiro": False,
            "magico": False,
            "velho": False,
            "hogwarts": False,
            "scooby": True,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },
        {
            "nome": "Velma",
            "humano": True,
            "homem": False,
            "ruivo": False,
            "oculos": True,
            "loiro": False,
            "fome": False,
            "dirige": False,
            "rabo": False,
            "coragem": True,
            "espada": False,
            "capuz": False,
            "aventura": False,
            "princesa": False,
            "vampiro": False,
            "magico": False,
            "velho": False,
            "hogwarts": False,
            "scooby": True,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },
        {
            "nome": "Daphne",
            "humano": True,
            "homem": False,
            "ruivo": True,
            "oculos": False,
            "loiro": False,
            "fome": False,
            "dirige": False,
            "rabo": False,
            "coragem": True,
            "espada": False,
            "capuz": False,
            "aventura": False,
            "princesa": False,
            "vampiro": False,
            "magico": False,
            "velho": False,
            "hogwarts": False,
            "scooby": True,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },
        {
            "nome": "Salsicha",
            "humano": True,
            "homem": True,
            "ruivo": False,
            "oculos": False,
            "loiro": False,
            "fome": True,
            "dirige": False,
            "rabo": False,
            "coragem": False,
            "espada": False,
            "capuz": False,
            "aventura": False,
            "princesa": False,
            "vampiro": False,
            "magico": False,
            "velho": False,
            "hogwarts": False,
            "scooby": True,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },
        {
            "nome": "Scooby-Doo",
            "humano": False,
            "homem": True,
            "ruivo": False,
            "oculos": False,
            "loiro": False,
            "fome": True,
            "dirige": False,
            "rabo": True,
            "coragem": False,
            "espada": False,
            "capuz": False,
            "aventura": False,
            "princesa": False,
            "vampiro": False,
            "magico": False,
            "velho": False,
            "hogwarts": False,
            "scooby": True,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },
        {
            "nome": "Scooby-Loo",
            "humano": False,
            "homem": True,
            "ruivo": False,
            "oculos": False,
            "loiro": False,
            "fome": False,
            "dirige": False,
            "rabo": True,
            "coragem": True,
            "espada": False,
            "capuz": False,
            "aventura": False,
            "princesa": False,
            "vampiro": False,
            "magico": False,
            "velho": False,
            "hogwarts": False,
            "scooby": True,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },

        #hora de aventura
        {
            "nome": "Finn",
            "humano": True,
            "homem": True,
            "ruivo": False,
            "oculos": False,
            "loiro": True,
            "fome": False,
            "dirige": False,
            "rabo": False,
            "coragem": True,
            "espada": True,
            "capuz": True,
            "aventura": True,
            "princesa": False,
            "vampiro": False,
            "magico": False,
            "velho": False,
            "hogwarts": False,
            "scooby": False,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },
        {
            "nome": "Jake",
            "humano": False,
            "homem": True,
            "ruivo": False,
            "oculos": False,
            "loiro": False,
            "fome": False,
            "dirige": False,
            "rabo": True,
            "coragem": True,
            "espada": False,
            "capuz": False,
            "aventura": True,
            "princesa": False,
            "vampiro": False,
            "magico": True,
            "velho": False,
            "hogwarts": False,
            "scooby": False,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },
        {
            "nome": "Princesa Jujuba",
            "humano": True,
            "homem": False,
            "ruivo": False,
            "oculos": False,
            "loiro": False,
            "fome": False,
            "dirige": False,
            "rabo": False,
            "coragem": True,
            "espada": False,
            "capuz": False,
            "aventura": True,
            "princesa": True,
            "vampiro": False,
            "magico": False,
            "velho": False,
            "hogwarts": False,
            "scooby": False,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },
        {
            "nome": "Marceline",
            "humano": True,
            "homem": False,
            "ruivo": False,
            "oculos": False,
            "loiro": False,
            "fome": False,
            "dirige": False,
            "rabo": False,
            "coragem": True,
            "espada": False,
            "capuz": False,
            "aventura": True,
            "princesa": False,
            "vampiro": True,
            "magico": True,
            "velho": False,
            "hogwarts": False,
            "scooby": False,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },
        {
            "nome": "Rei Gelado",
            "humano": True,
            "homem": True,
            "ruivo": False,
            "oculos": False,
            "loiro": False,
            "fome": False,
            "dirige": False,
            "rabo": False,
            "coragem": True,
            "espada": False,
            "capuz": False,
            "aventura": True,
            "princesa": False,
            "vampiro": False,
            "magico": True,
            "velho": True,
            "hogwarts": False,
            "scooby": False,
            "twilight": False,
            "heroi": False,
            "verde": False,
            "armadura": False,
            "superpoder": False
        },

	
        # Adicione os outros personagens aqui...
    ]
    return personagens
